dist: trusty
sudo: required
language: python
python:
        - "3.6"
script:
        - pytest

before_install:
        - sudo apt-get update -qq

install:
        - pip install numpy scipy pandas pytest pytest-cov codecov
        - pip install https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-1.5.1-cp36-cp36m-linux_x86_64.whl
        - pip install git+https://github.com/GPflow/GPflow
        - python setup.py install

script:
        - pytest --cov=./

after_success:
        - codecov --token=ebff81f1-b823-4d03-a600-599352c68f40
